version: "3.8"

networks:
  internalNetwork:
    name: internal_network

services:
  database:
    image: mysql:8.0.27
    container_name: anonrelay_database
    networks:
      - internalNetwork
    env_file:
      - .env
    ports:
      - "3306:3306"
    volumes:
      - ../var/docker/mysql:/var/lib/mysql

  traefik:
    image: traefik:2.5.6
    container_name: anonrelay_traefik
    networks:
      - internalNetwork
    command:
      - --api.insecure=true
      - --providers.docker=true
      - --providers.docker.exposedbydefault=false
      - --entrypoints.web.address=:80
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
  
  php:
    build:
      context: ../
      dockerfile: docker/Dockerfile
      target: php-fpm
      labels:
        org.opencontainers.image.source: https://github.com/iamfj/anonrelay
    image: ghcr.io/iamfj/anonrelay/php-fpm:latest
    container_name: anonrelay_php
    depends_on:
      - database
    networks:
      - internalNetwork
    volumes:
      - ../app:/var/www/app

  cli:
    build:
      context: ../
      dockerfile: docker/Dockerfile
      target: php-cli
      labels:
        org.opencontainers.image.source: https://github.com/iamfj/anonrelay
    image: ghcr.io/iamfj/anonrelay/php-cli:latest
    container_name: anonrelay_php_cli
    depends_on:
      - database
    working_dir: /var/www/app
    networks:
      - internalNetwork
    volumes:
      - ../app:/var/www/app

  cli-debug:
    build:
      context: ../
      dockerfile: docker/Dockerfile
      target: php-cli-debug
      labels:
        org.opencontainers.image.source: https://github.com/iamfj/anonrelay
    image: ghcr.io/iamfj/anonrelay/cli-debug:latest
    container_name: anonrelay_php_cli_debug
    depends_on:
      - database
    working_dir: /var/www/app
    networks:
      - internalNetwork
    volumes:
      - ../app:/var/www/app

  composer:
    build:
      context: ../
      dockerfile: docker/Dockerfile
      target: php-cli-composer
      labels:
        org.opencontainers.image.source: https://github.com/iamfj/anonrelay
    image: ghcr.io/iamfj/anonrelay/cli-composer:latest
    container_name: anonrelay_php_cli_composer
    working_dir: /var/www/app
    volumes:
      - ../app:/var/www/app

  nginx:
    image: nginx:1.21.5-alpine
    container_name: anonrelay_nginx
    depends_on:
      - traefik
      - php
    networks:
      - internalNetwork
    volumes:
      - ../app:/var/www/app
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    labels:
      - traefik.enable=true
      - traefik.http.routers.sampleApp.rule=Host("anonrelay.localhost")
      - traefik.http.routers.sampleApp.entrypoints=web
