#!/bin/bash
set -o nounset
set -o errexit
set -o pipefail

readonly SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && "pwd")"
readonly ROOT_DIR="$(realpath "$SCRIPT_DIR/../")"
readonly DOCKER_COMPOSE_FILE="$(realpath "$SCRIPT_DIR/../docker/docker-compose.yml")"

cd $ROOT_DIR

docker-compose -f "${DOCKER_COMPOSE_FILE}" \
  run --rm -u "$(id -u):$(id -g)" composer  "${@}"
