name: Reliability Workflow

on:
  push:
    branches:
      - main
  pull_request:
    types: [ opened, synchronize, reopened ]

jobs:
  installDevDeps:
    name: Install Development Dependencies
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Create empty .env file for docker tools
        run: touch ./docker/.env
      - name: Loading Production Composer Dependency Caches
        id: composer-dev-dependencies
        uses: actions/cache@v2
        with:
          path: app/vendor
          key: ${{ runner.os }}-${{ hashFiles('**/composer.lock') }}
      - name: Build Composer Development Dependencies
        if: steps.composer-dev-dependencies.outputs.cache-hit != 'true'
        run: ./scripts/composer install
      - uses: actions/upload-artifact@v2
        with:
          name: composer-dev-dependencies
          path: app/vendor

  installProdDeps:
    name: Install Production Dependencies
    runs-on: ubuntu-latest
    env:
      APP_ENV: prod
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Create empty .env file for docker tools
        run: touch ./docker/.env
      - name: Loading Production Composer Dependency Caches
        id: composer-prod-dependencies
        uses: actions/cache@v2
        with:
          path: app/vendor
          key: ${{ runner.os }}-${{ hashFiles('**/composer.lock') }}
      - name: Dump Environment Variables
        run: ./scripts/composer dump-env prod --empty
      - name: Build Composer Production Dependencies
        if: steps.composer-prod-dependencies.outputs.cache-hit != 'true'
        run: ./scripts/composer install --no-dev --optimize-autoloader

  runPhpUnitTestsWithCoverage:
    name: Run PhpUnit Tests with Coverage
    runs-on: ubuntu-latest
    needs:
      - installDevDeps
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Create empty .env file for docker tools
        run: touch ./docker/.env
      - name: Loading Development Composer Dependency Caches
        uses: actions/cache@v2
        with:
          path: app/vendor
          key: ${{ runner.os }}-${{ hashFiles('**/composer.lock') }}
      - name: Loading Cached Coverage
        id: phpunit-coverage
        uses: actions/cache@v2
        with:
          path: app/coverage
          key: ${{ runner.os }}-${{ hashFiles('**/(src|test)') }}
      - name: Run PhpUnit Tests with Coverage
        if: steps.phpunit-coverage.outputs.cache-hit != 'true'
        run: ./scripts/phpunit
      - name: Run PhpUnit Tests with Coverage
        run: ./scripts/phpunit
      - name: Analyze with SonarCloud
        if: steps.phpunit-coverage.outputs.cache-hit != 'true'
        uses: sonarsource/sonarcloud-github-action@master
        with:
          projectBaseDir: app
          args: >
            -Dsonar.organization=${{ secrets.SONAR_ORGANIZATION }}
            -Dsonar.projectKey=${{ secrets.SONAR_PROJECT_KEY }}
            -Dsonar.php.coverage.reportPaths=coverage/coverage.xml
